#!/bin/sh
set -x

if ! ip a l dev br0 > /dev/null
then
	ip link add br0 type bridge
  	ip addr add 192.168.0.1/24 b 192.168.0.255 dev br0
	ip link set dev br0 up
	iptables -t nat -A POSTROUTING -s 192.168.0.0/24 ! -d 192.168.0.0/24 -j MASQUERADE
	echo 1 > /proc/sys/net/ipv4/ip_forward
fi

if [ -n "$1" ];then
        ip tuntap add $1 mode tap user `whoami`
        ip link set $1 up
        sleep 0.5s
        ip link set $1 master br0
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi

